### ISSUE TITLE
Configuring issue in Manjaro Linux

### ISSUE THREAD

**Issue by ghost** [GPSnoopy/BelgianChocolateDuke3D#5]
When trying to run `./build-linux.sh` this error occurs:

```
CMake Error at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2Mixer (missing: SDL2_LIBRARIES SDL2_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2Mixer.cmake:27 (find_package_handle_standard_args)
  CMakeLists.txt:68 (find_package)
```

I checked if SDL2_mixer was installed, it was yet the aforementioned error was printed.

**Comment by GPSnoopy** [comment]
Did you install the dev package for SDL2_mixer?

**Comment by ghost** [comment]
I've since then migrated to Artix Linux. Just downloaded and compiled without any issues. Must've been an error with Manjaro's packages back then. All good now.
