### ISSUE TITLE
Continuous integration build cannot be obtained

### ISSUE THREAD

**Issue by NightFright2k19** [GPSnoopy/BelgianChocolateDuke3D#6]
I am checking under Actions -> Windows x64 CI (or Windows x86 CI), click on a workflow run (usually the topmost) and bam, 0 artifacts. Is there a way to obtain latest x86/x64 builds for Windows somehow without having to compile them manually?

**Comment by GPSnoopy** [comment]
I've added artifact upload for the Windows builds, though the maximum retention is 90 days. I've also tagged the latest build as Release 2022.07.27 so you can directly download it there.
